sudo: required
services:
  - docker

before_install:
   # build image using dev docker file in client folder context
  - docker build -t brnkimani/react-test -f ./client/Dockerfile.dev ./client

script:
  # test case will exit with a status of 0 or 1
  - docker run -e CI=true brnkimani/react-test npm test -- --coverage

after_success:
  - docker build -t brnkimani/multi-client ./client
  - docker build -t brnkimani/multi-nginx ./nginx
  - docker build -t brnkimani/multi-server ./server
  - docker build -t brnkimani/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to the docker hub
  - docker push brnkimani/multi-client
  - docker push brnkimani/multi-nginx
  - docker push brnkimani/multi-server
  - docker push brnkimani/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-430307034846'
  bucket_path: 'docket-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
